//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cc.isr.WinForms.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageBoxErrorSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageBoxErrorSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cc.isr.WinForms.Dialogs.ExceptionMessageBoxErrorSR", typeof(ExceptionMessageBoxErrorSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be completed..
        /// </summary>
        internal static string CantComplete {
            get {
                return ResourceManager.GetString("CantComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Show method can be called only once on an ExceptionMessageBox object. To display a new message, you must create a new instance of the ExceptionMessageBox class..
        /// </summary>
        internal static string CantReuseObject {
            get {
                return ResourceManager.GetString("CantReuseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send this message as e-mail..
        /// </summary>
        internal static string CantSendEmail {
            get {
                return ResourceManager.GetString("CantSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical details cannot be displayed..
        /// </summary>
        internal static string CantShowTechnicalDetailsError {
            get {
                return ResourceManager.GetString("CantShowTechnicalDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the following link to collect feedback: {0}..
        /// </summary>
        internal static string CantStartFeedback {
            get {
                return ResourceManager.GetString("CantStartFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the following help link: {0}..
        /// </summary>
        internal static string CantStartHelpLink {
            get {
                return ResourceManager.GetString("CantStartHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message cannot be copied to the clipboard..
        /// </summary>
        internal static string CopyToClipboardError {
            get {
                return ResourceManager.GetString("CopyToClipboardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify text for the button when Buttons = NewMessageBoxButtons.Custom..
        /// </summary>
        internal static string CustomButtonTextError {
            get {
                return ResourceManager.GetString("CustomButtonTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageLevelCount must be greater than 0..
        /// </summary>
        internal static string MessageLevelCountError {
            get {
                return ResourceManager.GetString("MessageLevelCountError", resourceCulture);
            }
        }
    }
}
