//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cc.isr.WinForms.ExceptionMessageBox.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageBuilderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageBuilderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cc.isr.WinForms.ExceptionMessageBox.Tests.ExceptionMessageBuilderResources", typeof(ExceptionMessageBuilderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Location:.
        /// </summary>
        internal static string CodeLocation {
            get {
                return ResourceManager.GetString("CodeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code: {0}.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Error: {0}).
        /// </summary>
        internal static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}).
        /// </summary>
        internal static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}, Error: {1}).
        /// </summary>
        internal static string ErrorSourceNumber {
            get {
                return ResourceManager.GetString("ErrorSourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Error Code: {0}.
        /// </summary>
        internal static string ExtendedErrorCode {
            get {
                return ResourceManager.GetString("ExtendedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Number: {0}.
        /// </summary>
        internal static string SqlError {
            get {
                return ResourceManager.GetString("SqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite Information.
        /// </summary>
        internal static string SqliteInfo {
            get {
                return ResourceManager.GetString("SqliteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number: {0}.
        /// </summary>
        internal static string SqlLineNumber {
            get {
                return ResourceManager.GetString("SqlLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure: {0}.
        /// </summary>
        internal static string SqlProcedure {
            get {
                return ResourceManager.GetString("SqlProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Information.
        /// </summary>
        internal static string SqlServerInfo {
            get {
                return ResourceManager.GetString("SqlServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name: {0}.
        /// </summary>
        internal static string SqlServerName {
            get {
                return ResourceManager.GetString("SqlServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server.
        /// </summary>
        internal static string SqlServerSource {
            get {
                return ResourceManager.GetString("SqlServerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity: {0}.
        /// </summary>
        internal static string SqlSeverity {
            get {
                return ResourceManager.GetString("SqlSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: {0}.
        /// </summary>
        internal static string SqlState {
            get {
                return ResourceManager.GetString("SqlState", resourceCulture);
            }
        }
    }
}
